set(MULTIARCH_TUPLE "arm-poky-linux-gnueabi")
set(TOOLCHAIN_ROOT "/opt/poky/1.6.3/sysroots/cortexa8t2hf-vfp-neon-poky-linux-gnueabi")
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_PREFIX_PATH ${CMAKE_SOURCE_DIR}/staging/${MULTIARCH_TUPLE})
set(CMAKE_SYSROOT "/opt/poky/1.6.3/sysroots/x86_64-pokysdk-linux")
set(CMAKE_SYSROOT_BIN_PATH "${CMAKE_SYSROOT}/usr/bin")
set(CMAKE_SYSROOT_BINUTIL_PATH "${CMAKE_SYSROOT_BIN_PATH}/${MULTIARCH_TUPLE}")
set(CMAKE_C_COMPILER "${CMAKE_SYSROOT_BINUTIL_PATH}/${MULTIARCH_TUPLE}-gcc")
set(CMAKE_C_FLAGS "-march=armv7-a -marm -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a8 --sysroot=${CMAKE_SYSROOT}")
set(CMAKE_CXX_COMPILER "${CMAKE_SYSROOT_BINUTIL_PATH}/${MULTIARCH_TUPLE}-g++")
set(CMAKE_CXX_FLAGS "-march=armv7-a -marm -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a8 --sysroot=${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_ROOT}")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)